config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'
  resources :cours
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cour.rb
class Cour < ApplicationRecord

    validates :title, :content, presence: true
    validates :title, uniqueness: true
    validates :stars, inclusion: { in: 0..5}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/cours_controller.rb
class CoursController < ApplicationController
  before_action :set_cours, only: [:show, :edit, :update, :destroy]
  def index
     @cours = Cour.all
  end

  def show

  end

  def new
    @cour = Cour.new
  end

  def create
    @cour = Cour.create(cours_params)
    redirect_to cours_path
  end

  def edit

  end

  def update
    @cour.update(cours_params)
    redirect_to cour_path(@cour.id)
  end

  def destroy
    @cour.destroy
    redirect_to cours_path
  end

  private

    def cours_params
      params.require(:cour).permit(:title, :stars, :content)
    end
    def set_cours
        @cour = Cour.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/views/cours/destroy.html.erb
<h1>Cours#destroy</h1>
<p>Find me in app/views/cours/destroy.html.erb</p>

app/views/cours/edit.html.erb
<div class="container">
    <div class="shadow p-3 m-5 bg-white rounded text-center ">
      <h1>Editer un cours <%= @cour.title %></h1>


        <%= simple_form_for @cour do |f| %>
          <%= f.input :title %>
          <%= f.input :stars, collection: 0..5 %>
          <%= f.input :content %>
          <%= f.button :submit %>
        <% end %>
    </div>
  </div>

app/views/cours/index.html.erb
<div class="text-center">
<h1>Liste des cours</h1>
</div>

<div class="container">
  <% @cours.each do |cour| %>

  <%= link_to cour do %>
    <div class="shadow p-3 mb-5 bg-white rounded d-flex justify-content-between">



      <div>
      <h2><%= cour.title %></h2>
      <p><%= "*" * cour.stars %><p>
      </div>

        <div>
          <%= cour.created_at.strftime("%D %B %Y") %>

        </div>

      </div>
  <% end %>


  <% end %>
</div>

app/views/cours/new.html.erb
<div class="container">
    <div class="shadow p-3 m-5 bg-white rounded text-center ">
      <h1>Nouveau cours</h1>

      <%= simple_form_for @cour do |f| %>
        <%= f.input :title %>
        <%= f.input :stars, collection: 0..5 %>
        <%= f.input :content%>
        <%= f.button :submit %>
      <% end %>
    </div>
</div>
  

app/views/cours/show.html.erb
<div class="container">
    <div class="shadow p-3 m-5 bg-white rounded text-center ">
      <%= link_to cours_path do %>
      <button type="button" class="close mt-1 " aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <% end %>
      <h1><%= @cour.title %></h1>


      <p><%= "*" * @cour.stars %><p>
        <p><b>
          <%= @cour.created_at.strftime("%D %B %Y") %>
        </b></p>

      <p> <%= @cour.content %><p>
      <%= link_to "Editer", edit_cour_path(@cour.id), class:"btn btn-warning" %>
      <%= link_to "Détruire", cour_path(@cour.id), method: :delete, class:"btn btn-danger" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= favicon_link_tag 'logo.png' %>
    <meta name="description" content="description">
    <meta name="image" content="logo.png">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="d-flex justify-content-between align-items-center px-4 py-2 border-bottom">
  <%= link_to (image_tag "logo.png", height: 50), root_path %>
  <% if user_signed_in? %>
    <%= link_to t(".sign_out", default: "Log out"), destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path %>
  <% end %>
</div>